import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/context/AuthContext";
import { TiendaProvider } from "@/context/TiendaContext"; // <-- Importa aquí
import { ProductoProvider } from "@/context/ProductoContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <TiendaProvider> {/* <-- Envolvés acá */}
              <ProductoProvider>
                {children}
              </ProductoProvider>
            </TiendaProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
